/** Тексты из lib/l10n/app_ru.arb — без импровизации. */
export const RU = {
  livesConvertTitle: 'Получить жизни',
  livesConvertSubtitle: 'Обменяйте кристалы на жизни',
  noLivesTitle: 'Нет жизней',
  noLivesHeroSubtitle: 'Кубик отдыхает — верните жизни и продолжите',
  livesShopLabel: 'Обмен кристаллов на жизни',
  livesBuyFrameTitle: 'Обмен на жизни',
  livesBuyFrameSub: 'Кристаллы на жизни',
  buyAction: 'Обменять',
  needMoreAction: 'Нужно',
  livesPackPrice: (n) => `Стоимость: ${n} крист.`,
  statLives: 'Жизни',
  crystals: 'Кристаллы',
  livesPackLabel: (n) => `+${n} жизней`,
  badgeBest: 'Лучшая цена',
  toCrystals: 'К кристаллам',
  livesGained: (n) => `+${n} жизней`,
  recentAttemptsTitle: 'Последние попытки',
  playAgain: 'Играть снова',
  scoreSavedToast: 'Результат сохранён!',
  savedScoreBadge: 'Сохранено',
  tabDaily: 'Ежедневно',
  tabShop: 'Покупки',
  tabRent: 'Аренда',
  tabEarn: 'Действия',
  giftReady: 'Готово!',
  claimGift: 'Забрать подарок',
  giftToast: (n) => `Подарок! +${n} кристаллов`,
  dailyStreakHint: 'Забирайте награду каждый день подряд',
  dailyStreakActive: (d) => `Серия ${d} дн. · пропуск сбрасывает на день 1`,
  periodDay: 'День',
  claim: 'Получить',
  claimed: 'Получено',
  completed: 'Выполнено',
  dailyToast: (n) => `Ежедневно +${n}`,
  dailyUnlockWait: (day, time) => `День ${day} разблокируется через ${time}`,
  dailyLockedHint: (day) => `День ${day} откроется по порядку после дня ${day - 1}`,
  plusTitle: 'Boost',
  plusActiveShort: 'Вкл',
  plusOfferTitle: 'Boost',
  rentJumpTitle: 'Прыжок',
  rentJumpSub: 'Второй палец — перепрыгнуть врага',
  rentHelmetTitle: 'Шлем',
  rentHelmetSub: 'Один удар без смерти за партию',
  rentMinsLabel: (m) => `${m} мин`,
  rentActive: (t) => `Активно · ${t}`,
  rentExtend: 'Продлить',
  rentBuy: 'Арендовать',
  rentNotEnough: 'Не хватает кристалов',
  rentDiscountBadge: (p) => `−${p}%`,
  rentInactive: 'Аренда временно недоступна',
  earnPreviewHint: 'Заглушки до подключения рекламы и SDK',
  earnBonusLocked: 'Сначала выполните условие в игре',
  shopWatchAd: 'Смотри и получи',
  shopWatchAdSub: 'Короткое видео · бесплатно',
  shopIapHint: 'Покупки за реальные деньги доступны в приложении Android.',
  online: 'онлайн',
  offline: 'офлайн',
  crystalsPlus: (n) => `+${n} кристаллов`,
  earnInstallBonus: 'Бонус за установку',
  earnInstallBonusSub: 'Приз за скачивание игры',
  earnSurvive10: 'Продержаться 10 секунд',
  earnSurvive10Sub: '10 секунд в одной партии',
  earnRecord20: 'Рекорд 20 секунд',
  earnRecord20Sub: 'Личный рекорд от 20 секунд',
  earnRisks5: '5 рисков за партию',
  earnRisks5Sub: 'Набрать 5 рисков в одной игре',
  earnWatchAd: 'Смотреть рекламу',
  earnWatchAdSub: 'Короткий ролик',
  earnSocialPost: 'Пост в соцсети',
  earnSocialPostSub: 'Расскажите друзьям',
  earnNotifications: 'Уведомления',
  earnNotificationsSub: 'Разрешить push-уведомления',
  earnRateApp: 'Оценить игру',
  earnRateAppSub: 'Звёзды в магазине',
  earnInviteFriend: 'Пригласить друга',
  earnInviteFriendSub: 'Поделиться ссылкой',
  shopFree: 'FREE',
  plusNoAdsShort: 'Без рекламы',
  plusCrystalsDoubleShort: '×2',
  premiumTimesLocked: (mult) => `×${mult} с Boost`,
  premiumTimesBase: (base, mult) => `${base} × ${mult}`,
  plusCancel: 'Отменить подписку',
  plusToast: 'Boost · ежедневно ×2',
  plusCancelledToast: 'Boost отключён',
  plusManageTitle: 'Управление Boost',
  plusOfferTitle: 'Подписка Boost',
  plusOfferSubtitle:
    'Boost — еженедельная подписка за $1. Без рекламы и ×2 кристаллы в ежедневном бонусе. Отменить можно в этом окне (оплата через Google Play / App Store — позже).',
  plusSubscribe: (price) => `Подписаться · ${price}`,
  plusManageSubtitle:
    'Boost даёт бонусы в игре. Пока это локальный preview — после подключения магазина списание пойдёт через Google Play / App Store.',
  plusManageBenefitAds: 'Без рекламы',
  plusManageBenefitDaily: '×2 кристаллы в ежедневном бонусе',
  plusManagePrice: (price) => `Стоимость: ${price}`,
  plusManageNextCharge: (date) => `Следующее списание: ${date}`,
  plusBack: 'Назад',
  newScore: 'Новый результат',
  newScoreKicker: 'НОВЫЙ РЕЗУЛЬТАТ',
  share: 'Сохранить',
  shareSocial: 'Поделиться',
  ok: 'OK',
  playAgain: 'Ещё раз',
  appTitle: 'Untouch',
  playInfoNear: 'Риск',
  playInfoRun: 'Пробег',
  riskCrystalsEarned: (n) => `+${n}`,
  periodAll: 'Всё время',
  periodYear: 'Год',
  periodMonth: 'Месяц',
  periodWeek: 'Неделя',
  periodDay: 'День',
  periodMine: 'Мои попытки',
  leaderboardTitle: 'Рейтинг',
  offline: 'Локально',
  autoSavedBadge: 'Сохранено',
  recordBeatToast: (sec) => `🎉 Новый рекорд! Вы побили сами себя: ${sec} с. Сохранено!`,
  recordDayToast: (sec) => `⭐ Новый рекорд дня: ${sec} с! Результат сохранён!`,
  autoSaveHint: 'Рекорды сохраняются автоматически при их улучшении',
  emptyPeriodRecords: 'Пока нет заездов за этот период — сыграйте партию и установите рекорд!',
  bestForDay: 'Рекорд за сегодня',
  bestForWeek: 'Рекорд за неделю',
  bestForMonth: 'Рекорд за месяц',
  bestForAll: 'Рекорд за всё время',
  totalAttemptsLabel: (n) => `Всего попыток: ${n}`,
  colRank: '#',
  colPlayer: 'Игрок',
  colBoosts: 'Бусты',
  colTime: 'Время',
  colRisk: 'Риск',
  colRun: 'Пробег',
  topPeriodAll: 'ТОП ЗА ВСЁ ВРЕМЯ',
  topPeriodMonth: 'ТОП ЗА МЕСЯЦ',
  topPeriodWeek: 'ТОП ЗА НЕДЕЛЮ',
  topPeriodDay: 'ТОП ЗА СЕГОДНЯ',
  topPeriodMine: 'МОИ ЗАЕЗДЫ',
  youTag: 'Вы',
  jumpActive: 'Прыжок',
  helmetActive: 'Шлем',
  shareCardTitle: 'Поделиться результатом',
  shareSendBtn: 'Отправить в Telegram',
  shareDownloadBtn: 'Скачать картинку',
  shareCancelBtn: 'Закрыть',
  shareBoast: (time) => `Я продержался ${time} сек в Untouch!`,
  shareChallenge: 'Сможешь побить мой рекорд?',
  shareBotHandle: '@UntouchGameBot',
  shareBotUrl: 'https://t.me/UntouchGameBot',
  shareImageSavedToast: 'Картинка сохранена!',
  riskTipHow: 'Риск засчитывается, когда вы едва разминулись с врагом — близко, но без касания.',
  riskTipConvert: (every, reward) => `В конце партии: каждые ${every} рисков = ${reward} кристалл(ов).`,
  runTipHow: 'Пробег — путь кубика в шагах. 1 шаг = 0,1 ширины героя (на всех экранах одинаково).',
  runTipConvert: (every, reward) => `В конце партии: каждые ${every} шагов = ${reward} кристалл(ов).`,
};

export function earnTitle(id) {
  const map = {
    install_bonus: RU.earnInstallBonus,
    survive_10s: RU.earnSurvive10,
    record_20s: RU.earnRecord20,
    risks_5: RU.earnRisks5,
    watch_ad: RU.earnWatchAd,
    social_post: RU.earnSocialPost,
    enable_notifications: RU.earnNotifications,
    rate_app: RU.earnRateApp,
    invite_friend: RU.earnInviteFriend,
  };
  return map[id] ?? id;
}

export function earnSubtitle(id) {
  const map = {
    install_bonus: RU.earnInstallBonusSub,
    survive_10s: RU.earnSurvive10Sub,
    record_20s: RU.earnRecord20Sub,
    risks_5: RU.earnRisks5Sub,
    watch_ad: RU.earnWatchAdSub,
    social_post: RU.earnSocialPostSub,
    enable_notifications: RU.earnNotificationsSub,
    rate_app: RU.earnRateAppSub,
    invite_friend: RU.earnInviteFriendSub,
  };
  return map[id] ?? '';
}
