/** Тексты из lib/l10n/app_ru.arb — без импровизации. */
export const RU = {
  livesConvertTitle: 'Получить жизни',
  livesConvertSubtitle: 'Обменяйте кристалы на жизни',
  noLivesTitle: 'Нет жизней',
  noLivesHeroSubtitle: 'Кубик отдыхает — верните жизни и продолжите',
  livesShopLabel: 'Обмен кристаллов на жизни',
  livesBuyFrameTitle: 'Обмен на жизни',
  livesBuyFrameSub: 'Кристаллы на жизни',
  buyAction: 'Обменять',
  needMoreAction: 'Нужно',
  livesPackPrice: (n) => `Стоимость: ${n} крист.`,
  statLives: 'Жизни',
  crystals: 'Кристаллы',
  livesPackLabel: (n) => `+${n} жизней`,
  badgeBest: 'Лучшая цена',
  toCrystals: 'К кристаллам',
  livesGained: (n) => `+${n} жизней`,
  recentAttemptsTitle: 'Последние попытки',
  playAgain: 'Играть снова',
  scoreSavedToast: 'Результат сохранён!',
  savedScoreBadge: 'Сохранено',
  tabDaily: 'Ежедневно',
  tabShop: 'Покупки',
  tabRent: 'Аренда',
  tabEarn: 'Действия',
  giftReady: 'Готово!',
  claimGift: 'Забрать подарок',
  giftToast: (n) => `Подарок! +${n} кристаллов`,
  dailyStreakHint: 'Забирайте награду каждый день подряд',
  dailyStreakActive: (d) => `Серия ${d} дн. · пропуск сбрасывает на день 1`,
  periodDay: 'День',
  claim: 'Получить',
  claimed: 'Получено',
  completed: 'Выполнено',
  dailyToast: (n) => `Ежедневно +${n}`,
  dailyUnlockWait: (day, time) => `День ${day} разблокируется через ${time}`,
  dailyLockedHint: (day) => `День ${day} откроется по порядку после дня ${day - 1}`,
  plusTitle: 'Plus',
  plusActiveShort: 'Вкл',
  rentJumpTitle: 'Прыжок',
  rentJumpSub: 'Второй палец — перепрыгнуть врага',
  rentHelmetTitle: 'Шлем',
  rentHelmetSub: 'Один удар без смерти за партию',
  rentMinsLabel: (m) => `${m} мин`,
  rentActive: (t) => `Активно · ${t}`,
  rentExtend: 'Продлить',
  rentBuy: 'Арендовать',
  rentNotEnough: 'Не хватает кристалов',
  rentDiscountBadge: (p) => `−${p}%`,
  rentInactive: 'Аренда временно недоступна',
  earnBonusLocked: 'Сначала выполните условие в игре',
  shopWatchAd: 'Смотри и получи',
  shopWatchAdSub: 'Короткое видео · бесплатно',
  shopIapHint: 'Оплата Telegram Stars. Кристаллы приходят после подтверждения платежа.',
  shopPayWait: 'Открываем оплату…',
  shopPayNeedTelegram: 'Покупки доступны внутри Telegram.',
  shopPayFailed: 'Не удалось открыть оплату. Попробуйте ещё раз.',
  shopPayCancelled: 'Оплата отменена.',
  shopPayPending: 'Проверяем платёж…',
  shopPaidCrystals: (n) => `+${n} кристаллов`,
  shopPaidPlus: (days) => `Plus на ${days} дней`,
  online: 'онлайн',
  offline: 'офлайн',
  crystalsPlus: (n) => `+${n} кристаллов`,
  earnInstallBonus: 'Бонус за установку',
  earnInstallBonusSub: 'Приз за скачивание игры',
  earnSurvive10: 'Продержаться 10 секунд',
  earnSurvive10Sub: '10 секунд в одной партии',
  earnRecord20: 'Рекорд 20 секунд',
  earnRecord20Sub: 'Личный рекорд от 20 секунд',
  earnRisks5: '5 рисков за партию',
  earnRisks5Sub: 'Набрать 5 рисков в одной игре',
  earnWatchAd: 'Смотреть рекламу',
  earnWatchAdSub: 'Короткий ролик',
  earnSocialPost: 'Пост в соцсети',
  earnSocialPostSub: 'Расскажите друзьям',
  earnNotifications: 'Уведомления',
  earnNotificationsSub: 'Разрешить боту писать вам',
  earnNotificationsNeedGrant: 'Нужно разрешить, чтобы получить кристаллы',
  earnNotificationsNeedTelegram: 'Разрешение на сообщения доступно внутри Telegram.',
  earnNotificationsAlready: 'Уведомления уже включены',
  earnRateApp: 'Оценить игру',
  earnRateAppSub: 'Звёзды в магазине',
  earnInviteFriend: 'Пригласить друга',
  earnInviteFriendSub: (n) => `За каждого друга, который откроет игру, +${n} кристаллов`,
  earnInviteWaiting: 'Пока никто не перешёл по ссылке. Когда друг откроет игру, он появится здесь.',
  earnInviteListTitle: 'Кого пригласили',
  earnInviteVisited: 'Перешёл',
  earnInviteGot: (n) => `+${n}`,
  earnInviteShareText: ({ timeSec, bonus } = {}) => {
    const record = timeSec
      ? `Заходи, попробуй побить мой рекорд! Я продержался ${timeSec} сек.`
      : 'Заходи, попробуй Untouch — уводи кубик от красных и бей рекорд.';
    const gift = bonus
      ? ` Если зайдёшь сейчас, получишь бонус новичка — ${bonus} кристаллов.`
      : '';
    return `${record}${gift}`;
  },
  earnInviteLinkLabel: 'Перейти в бот с игрой',
  earnInvitePreparing: 'Готовим приглашение…',
  earnInviteShared: 'Ссылка отправлена. Когда друг откроет игру, он появится в списке, и вы получите кристаллы.',
  earnInviteForwardFromBot: 'Сообщение уже в чате с ботом — перешлите его другу. Ссылка выглядит как «Перейти в бот с игрой».',
  earnInviteNeedTelegram: 'Приглашения работают внутри Telegram.',
  profileSettings: 'Настройки',
  profileMusic: 'Фоновая музыка',
  profileHaptic: 'Виброотклик',
  profileLightTheme: 'Светлая тема',
  earnInviteRewardToast: (n, friends = 1) =>
    friends > 1 ? `Друзья зашли в игру! +${n} кристаллов` : `Друг зашёл в игру! +${n} кристаллов`,
  earnInviteWelcome: 'Вы открыли игру по приглашению друга',
  shopFree: 'FREE',
  plusNoAdsShort: 'Без рекламы на результате',
  plusCrystalsDoubleShort: '×2',
  premiumTimesLocked: (mult) => `×${mult} с Plus`,
  premiumTimesBase: (base, mult) => `${base} × ${mult}`,
  plusCancel: 'Отменить в Telegram',
  plusToast: 'Plus · ежедневно ×2 · без рекламы на результате',
  plusCancelledToast: 'Plus отключён',
  plusManageTitle: 'Управление Plus',
  plusOfferTitle: 'Подписка Plus',
  plusOfferSubtitle: (days) =>
    days === 7
      ? 'Plus на неделю: ежедневный бонус ×2 и без рекламы на экране результата. Ролик за кристаллы остаётся. Telegram не списывает Stars раз в неделю сам — продлевается повторной покупкой.'
      : `Plus на ${days} дней: ежедневный бонус ×2 и без рекламы на экране результата. Ролик за кристаллы остаётся. Отмена — в платежах Telegram.`,
  plusSubscribe: (price) => `Подписаться · ${price}`,
  plusManageSubtitle:
    'Plus удваивает ежедневный бонус и убирает рекламу при просмотре результатов. Смотреть рекламу за кристаллы можно как обычно.',
  plusManageBenefitDaily: '×2 кристаллы в ежедневном бонусе',
  plusManageBenefitAds: 'Без рекламы на экране результата',
  plusDailyOffHint: '×2 к бонусу · без рекламы на результате',
  plusDailyOnHint: (date) => `×2 и без рекламы на результате · до ${date}`,
  plusDailyCtaOff: 'Подключить',
  plusDailyCtaOn: 'Подробнее',
  adReadyLbl: 'Ролик',
  plusManagePrice: (price) => `Стоимость: ${price}`,
  plusManageNextCharge: (date) => `Действует до: ${date}`,
  plusCancelInTelegram: 'Отменить можно в платежах Telegram (Stars).',
  plusBack: 'Назад',
  newScore: 'Новый результат',
  resultScoreTag: '⚡ ОЧКИ ПОПЫТКИ',
  newScoreKicker: 'НОВЫЙ РЕЗУЛЬТАТ',
  share: 'Сохранить',
  shareSocial: 'Поделиться',
  ok: 'OK',
  playAgain: 'Ещё раз',
  appTitle: 'Untouch',
  playInfoNear: 'Риск',
  playInfoRun: 'Шаги',
  statTipTitle: 'Как это работает',
  riskTipHow: 'Риск засчитывается, когда вы едва разминулись с врагом — близко, но без касания.',
  riskTipConvert: (every, reward) => `В конце попытки: каждые ${every} рисков = ${reward} кристалл(ов).`,
  runTipHow: 'Шаги — путь кубика за попытку. 1 шаг = 0,1 ширины героя, поэтому на всех экранах считается одинаково.',
  runTipConvert: (every, reward) => `В конце попытки: каждые ${every} шагов = ${reward} кристалл(ов).`,
  jumpTipHow: 'Прыжок: второй палец на экране — кубик перепрыгивает врага.',
  jumpTipState: (on) => (on ? 'В этой попытке прыжок был включён.' : 'В этой попытке прыжок был выключен.'),
  helmetTipHow: 'Шлем: один удар врага за попытку не заканчивает игру.',
  helmetTipState: (on) => (on ? 'В этой попытке шлем был включён.' : 'В этой попытке шлем был выключен.'),
  emptyPeriodRecords: 'Пока нет попыток за этот период — сыграйте и установите рекорд!',
  colRun: 'Шаги',
  topPeriodMine: 'МОИ ПОПЫТКИ',
  shopAdWait: 'Открываем ролик…',
  shopAdNotReady: 'Реклама скоро появится. Загляните позже.',
  shopAdFailed: 'Ролик не удалось показать. Попробуйте позже.',
  shopAdSkipped: 'Нужно досмотреть ролик, чтобы получить кристаллы.',
  shopAdFailTitle: 'Телевизор барахлит',
  shopAdFailBody: 'Ролик не загрузился. Кубик уже чинит — загляните чуть позже.',
  shopAdFailOk: 'Понятно',
  shopAdHintTitle: 'Минутка у телевизора',
  shopAdHintBody: 'Ролик около минуты. Его нельзя свернуть. Кристаллы — только если досмотреть до конца.',
  shopAdHintSkip: 'Больше не показывать',
  shopAdHintCancel: 'Отмена',
  shopAdHintOk: 'Смотреть',
  earnPreviewHint: 'Награды за действия в игре.',
  riskCrystalsEarned: (n) => `+${n}`,
  periodAll: 'Всё время',
  periodYear: 'Год',
  periodMonth: 'Месяц',
  periodWeek: 'Неделя',
  periodDay: 'День',
  periodMine: 'Мои попытки',
  leaderboardTitle: 'Рейтинг',
  offline: 'Локально',
  autoSavedBadge: 'Сохранено',
  recordBeatToast: (sec) => `🎉 Новый рекорд! Вы побили сами себя: ${sec} с. Сохранено!`,
  recordDayToast: (sec) => `⭐ Новый рекорд дня: ${sec} с! Результат сохранён!`,
  autoSaveHint: 'Рекорды сохраняются автоматически при их улучшении',
  leaderboardLoading: 'Загружаем рейтинг…',
  bestForDay: 'Рекорд за сегодня',
  bestForWeek: 'Рекорд за неделю',
  bestForMonth: 'Рекорд за месяц',
  bestForAll: 'Рекорд за всё время',
  totalAttemptsLabel: (n) => `Всего попыток: ${n}`,
  colRank: '#',
  colPlayer: 'Игрок',
  colBoosts: 'Бусты',
  colTime: 'Время',
  colRisk: 'Риск',
  topPeriodAll: 'ТОП ЗА ВСЁ ВРЕМЯ',
  topPeriodMonth: 'ТОП ЗА МЕСЯЦ',
  topPeriodWeek: 'ТОП ЗА НЕДЕЛЮ',
  topPeriodDay: 'ТОП ЗА СЕГОДНЯ',
  youTag: 'Вы',
  jumpActive: 'Прыжок',
  helmetActive: 'Шлем',
  shareCardTitle: 'Поделиться результатом',
  shareSendBtn: 'Отправить в Telegram',
  shareDownloadBtn: 'Скачать картинку',
  shareCancelBtn: 'Закрыть',
  shareBoast: (time) => `Я продержался ${time} сек в Untouch!`,
  shareChallenge: 'Сможешь побить мой рекорд?',
  shareBotHandle: '@UntouchGameBot',
  shareBotUrl: 'https://t.me/UntouchGameBot',
  shareImageSavedToast: 'Картинка сохранена!',
};

export function earnTitle(id) {
  const map = {
    install_bonus: RU.earnInstallBonus,
    survive_10s: RU.earnSurvive10,
    record_20s: RU.earnRecord20,
    risks_5: RU.earnRisks5,
    watch_ad: RU.earnWatchAd,
    social_post: RU.earnSocialPost,
    enable_notifications: RU.earnNotifications,
    rate_app: RU.earnRateApp,
    invite_friend: RU.earnInviteFriend,
  };
  return map[id] ?? id;
}

export function earnSubtitle(id) {
  const map = {
    install_bonus: RU.earnInstallBonusSub,
    survive_10s: RU.earnSurvive10Sub,
    record_20s: RU.earnRecord20Sub,
    risks_5: RU.earnRisks5Sub,
    watch_ad: RU.earnWatchAdSub,
    social_post: RU.earnSocialPostSub,
    enable_notifications: RU.earnNotificationsSub,
    rate_app: RU.earnRateAppSub,
  };
  return map[id] ?? '';
}
